"""
Automated Defense & Firewall API Routes
Endpoints to monitor active defense policies, manage dynamic firewall rules,
isolate/restore Cyber Twin devices, and download incident reports.
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any, List
import time
from app.models.schemas import (
    FirewallRule, FirewallRuleCreate, AutomatedDefenseState,
    SecurityAlert, IncidentReport
)
from app.core.defense_engine import defense_engine
from app.core.cyber_twin import cyber_twin
from app.core.attack_simulator import attack_sim
from app.core import database

router = APIRouter(prefix="/api/defense", tags=["Automated Defense"])

@router.get("/status", response_model=AutomatedDefenseState)
def get_defense_status():
    """Returns current active automated defense status and live firewall rules."""
    rules = database.get_active_firewall_rules()
    quarantined = [d_id for d_id, d in cyber_twin.devices.items() if d.status == "QUARANTINED"]
    
    return AutomatedDefenseState(
        auto_defense_active=defense_engine.auto_defense_enabled,
        active_rules_count=len(rules),
        quarantined_nodes=quarantined,
        total_mitigations_executed=defense_engine.total_mitigations,
        firewall_rules=[
            FirewallRule(
                rule_id=r["rule_id"],
                source_ip=r["source_ip"],
                destination_ip=r["destination_ip"],
                port=r.get("port"),
                protocol=r["protocol"],
                action=r["action"],
                reason=r["reason"],
                created_at=r["created_at"],
                expires_at=r.get("expires_at"),
                is_active=bool(r["is_active"]),
                mitre_attack_id=r.get("mitre_attack_id")
            ) for r in rules
        ]
    )

@router.post("/toggle")
def toggle_auto_defense(enabled: bool):
    """Enables or disables autonomous threat mitigation."""
    status = defense_engine.toggle_auto_defense(enabled)
    return {"auto_defense_enabled": status}

@router.post("/rules", response_model=FirewallRule)
def create_manual_rule(rule_req: FirewallRuleCreate):
    """Creates a manual firewall rule."""
    rule_dict = defense_engine.manual_add_rule(rule_req.dict())
    return FirewallRule(
        rule_id=rule_dict["rule_id"],
        source_ip=rule_dict["source_ip"],
        destination_ip=rule_dict["destination_ip"],
        port=rule_dict.get("port"),
        protocol=rule_dict["protocol"],
        action=rule_dict["action"],
        reason=rule_dict["reason"],
        created_at=rule_dict["created_at"],
        expires_at=rule_dict.get("expires_at"),
        is_active=bool(rule_dict["is_active"]),
        mitre_attack_id=rule_dict.get("mitre_attack_id")
    )

@router.delete("/rules/{rule_id}")
def delete_rule(rule_id: str):
    """Deletes an active firewall rule."""
    deleted = defense_engine.remove_rule(rule_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Firewall rule not found")
    return {"status": "SUCCESS", "message": f"Rule {rule_id} removed."}

@router.post("/quarantine/{device_id}")
def quarantine_node(device_id: str):
    """Manually isolates a node in the Cyber Twin."""
    if device_id not in cyber_twin.devices:
        raise HTTPException(status_code=404, detail="Device not found")
    defense_engine.manual_quarantine(device_id)
    return {"status": "SUCCESS", "message": f"Device {device_id} isolated into quarantine."}

@router.post("/restore/{device_id}")
def restore_node(device_id: str):
    """Restores a quarantined device back to normal operation."""
    if device_id not in cyber_twin.devices:
        raise HTTPException(status_code=404, detail="Device not found")
    defense_engine.manual_restore(device_id)
    return {"status": "SUCCESS", "message": f"Device {device_id} restored to NORMAL state."}

@router.get("/alerts", response_model=List[SecurityAlert])
def get_alerts(limit: int = 50):
    """Retrieves recent security alerts generated by AI and Automated Defense."""
    raw_alerts = database.get_recent_alerts(limit)
    return [
        SecurityAlert(
            id=a["id"],
            timestamp=a["timestamp"],
            severity=a["severity"],
            title=a["title"],
            description=a["description"],
            source_device=a["source_device"],
            target_device=a.get("target_device"),
            threat_score=a["threat_score"],
            defense_applied=bool(a["defense_applied"]),
            remediation_action=a.get("remediation_action")
        ) for a in raw_alerts
    ]

@router.get("/report", response_model=IncidentReport)
def generate_incident_report():
    """Generates an executive security audit report of all simulated threats and defense actions."""
    alerts = get_alerts(100)
    quarantined = [d.name for d in cyber_twin.devices.values() if d.status == "QUARANTINED"]
    rules = database.get_active_firewall_rules()
    
    summary = (
        f"NetClone Cyber Twin Defense Audit: {len(alerts)} threat events recorded. "
        f"{len(rules)} active dynamic firewall rules enforcing perimeter protection. "
        f"{len(quarantined)} IoT devices currently isolated in quarantine. "
        f"AI threat detection models operating with multi-layer MLSA authentication safeguards."
    )
    
    return IncidentReport(
        generated_at=time.time(),
        total_threats_detected=len(alerts),
        attacks_simulated=attack_sim.packets_generated,
        firewall_rules_enacted=len(rules),
        quarantined_devices=quarantined,
        mlsa_negative_db_inspections=database.get_connection().execute("SELECT count(*) FROM users").fetchone()[0],
        alerts=alerts,
        executive_summary=summary
    )
